{{- if .Values.api.core.ingress.enabled -}}
{{- $fullName := include "vcwaltid.fullname" . -}}
{{- $servicePort := .Values.api.core.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "vcwaltid.fullname" . }}-core
  labels:
    {{ include "vcwaltid.labels" . | nindent 4 }}
  {{- if .Values.api.core.ingress.annotations }}
  annotations:
    {{- with .Values.api.core.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
      {{- end }}
  {{- end }}
spec:
  {{- if .Values.api.core.ingress.tls }}
  tls:
    {{- range .Values.api.core.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  {{- range .Values.api.core.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
        - path: {{ . }}
          pathType: Prefix
          backend:
            service:
              name: {{ $fullName }}
              port: 
                number: {{ $servicePort }}
        {{- end }}
  {{- end }}
{{- end }}
